#!/usr/bin/env python3
"""Static page builder: puts the shared header and footer into every page.

No dependencies, Python 3.8+. Pages are written by hand in src/*.html, and shared
pieces live in src/partials/. The built pages are written to the repository root,
which is what GitHub Pages serves, so commit both src/ and the generated pages.

    python3 build.py           build every page
    python3 build.py --check   write nothing; exit 1 if a built page is out of date

In a page or a partial:

    <!-- @include header -->    inserted from src/partials/header.html, keeping the
                                indentation of the line the comment is on
    {{home}}                    "" on index.html, "index.html" on every other page, so the
                                same header links to #about on the home page and to
                                index.html#about everywhere else
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
PARTIALS = SRC / "partials"

INCLUDE = re.compile(r"^([ \t]*)<!-- @include ([\w-]+) -->[ \t]*$", re.MULTILINE)
VARIABLE = re.compile(r"\{\{(\w+)\}\}")


def fail(message):
    sys.exit("build.py: " + message)


def load_partial(name):
    path = PARTIALS / (name + ".html")
    if not path.is_file():
        fail("unknown partial '%s' (expected %s)" % (name, path.relative_to(ROOT)))
    return path.read_text(encoding="utf-8").rstrip("\n")


def render(page):
    """Return the built HTML for one source page."""
    variables = {"home": "" if page.name == "index.html" else "index.html"}
    html = page.read_text(encoding="utf-8")

    def include(match):
        indent, name = match.group(1), match.group(2)
        lines = load_partial(name).split("\n")
        return "\n".join((indent + line) if line.strip() else line for line in lines)

    html = INCLUDE.sub(include, html)

    def variable(match):
        name = match.group(1)
        if name not in variables:
            fail("unknown variable {{%s}} in %s" % (name, page.relative_to(ROOT)))
        return variables[name]

    html = VARIABLE.sub(variable, html)

    banner = "<!-- Generated by build.py from src/%s. Edit the source, not this file. -->" % page.name
    return re.sub(r"(<!DOCTYPE html>\n)", r"\1" + banner + "\n", html, count=1, flags=re.IGNORECASE)


def main(argv):
    check = "--check" in argv
    unknown = [a for a in argv if a not in ("--check",)]
    if unknown:
        fail("unknown option %s (only --check is supported)" % unknown[0])

    pages = sorted(SRC.glob("*.html"))
    if not pages:
        fail("no pages found in src/")

    stale = []
    for page in pages:
        built = render(page)
        target = ROOT / page.name
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == built:
            continue
        stale.append(page.name)
        if not check:
            target.write_text(built, encoding="utf-8")
            print("built  " + page.name)

    if check:
        if stale:
            print("out of date: " + ", ".join(stale))
            print("run: python3 build.py")
            return 1
        print("all %d pages up to date" % len(pages))
        return 0

    print("%d pages, %d written" % (len(pages), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
